OGSNTweakItem("filcher.SFGuideCooking","StaticModel","Book")
OGSNTweakItem("filcher.SFCookingGuide","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideEletronics","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideEngineering","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideFishing","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideMechanics","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideMetalworking","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideRadio","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideTrapping","StaticModel","Book")
OGSNTweakItem("filcher.SFBookFarm","StaticModel","Book")
OGSNTweakItem("filcher.SFGuideTrapping","ReplaceOnUse","SFGuideTrapping")

OGSNTweakItem("filcher.SFGuideEngineering","TeachedRecipes","Make Noise Maker;Make Smoke Bomb;Make Aerosol bomb;Make Flame bomb;Make Pipe bomb")
OGSNTweakItem("filcher.SFGuideMetalworking","TeachedRecipes","Make Metal Stairs;Make Metal Walls;Make Metal Roof;Make Metal Containers;Make Metal Fences;Make Metal Sheet;Make Small Metal Sheet")
